package `in`.jphe.storyvox.data.repository

import `in`.jphe.storyvox.data.db.dao.InboxEventDao
import `in`.jphe.storyvox.data.db.entity.InboxEvent
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * Issue #383 — repository-level coverage for the cross-source Inbox.
 *
 * The DAO is faked to keep these tests on plain JVM. The fake mirrors
 * the production SQL invariants we actually depend on:
 *   - insert assigns an autogenerated id
 *   - observeAll emits ORDER BY ts DESC
 *   - latestUnreadForFiction filters by (sourceId, fictionId) AND
 *     isRead = 0, returns the most recent
 *   - markRead / markAllRead flip the isRead flag and update the
 *     unread count
 *
 * Tests here cover the *coalescing* logic that lives in the
 * repository (not the DAO) — the InboxRepository.record contract
 * promises that consecutive new-chapter polls update the existing
 * unread row in place rather than stacking duplicates.
 */
@OptIn(ExperimentalCoroutinesApi::class)
class InboxRepositoryImplTest {

    private class FakeInboxEventDao : InboxEventDao {
        val rows = mutableMapOf<Long, InboxEvent>()
        private var nextId = 1L
        private val feed = MutableStateFlow<List<InboxEvent>>(emptyList())
        private val unread = MutableStateFlow(0)

        private fun rebuild() {
            feed.value = rows.values.sortedByDescending { it.ts }
            unread.value = rows.values.count { !it.isRead }
        }

        override fun observeAll(): Flow<List<InboxEvent>> = feed
        override fun observeAfter(afterTs: Long): Flow<List<InboxEvent>> =
            MutableStateFlow(rows.values.filter { it.ts > afterTs }.sortedByDescending { it.ts })

        override fun observeUnreadCount(): Flow<Int> = unread

        override suspend fun insert(event: InboxEvent): Long {
            val id = nextId++
            rows[id] = event.copy(id = id)
            rebuild()
            return id
        }

        override suspend fun markRead(id: Long) {
            rows[id]?.let { rows[id] = it.copy(isRead = true) }
            rebuild()
        }

        override suspend fun markAllRead() {
            rows.replaceAll { _, v -> v.copy(isRead = true) }
            rebuild()
        }

        override suspend fun latestUnreadForFiction(
            sourceId: String,
            fictionId: String,
        ): InboxEvent? = rows.values
            .filter { it.sourceId == sourceId && it.fictionId == fictionId && !it.isRead }
            .maxByOrNull { it.ts }

        override suspend fun coalesceInPlace(
            id: Long,
            title: String,
            body: String?,
            ts: Long,
            deepLinkUri: String?,
            additionalCount: Int,
        ) {
            rows[id]?.let {
                rows[id] = it.copy(
                    title = title,
                    body = body,
                    ts = ts,
                    deepLinkUri = deepLinkUri,
                    newChapterCount = it.newChapterCount + additionalCount,
                )
            }
            rebuild()
        }

        override suspend fun deleteAll() {
            rows.clear()
            rebuild()
        }
    }

    @Test fun `record assigns id and emits in feed`() = runTest {
        val dao = FakeInboxEventDao()
        val repo = InboxRepositoryImpl(dao)

        val id = repo.record(
            sourceId = "royalroad",
            fictionId = "rr:42",
            chapterId = "rr:42:7",
            title = "1 new chapter in Mother of Learning",
            body = null,
            ts = 1_000L,
            deepLinkUri = "storyvox://reader/rr:42/rr:42:7",
        )

        assertEquals(1L, id)
        val all = repo.observeAll().first()
        assertEquals(1, all.size)
        assertEquals("royalroad", all.first().sourceId)
        assertEquals(1, repo.observeUnreadCount().first())
    }

    @Test fun `record coalesces consecutive unread events for same fiction`() = runTest {
        val dao = FakeInboxEventDao()
        val repo = InboxRepositoryImpl(dao)

        repo.record(
            sourceId = "royalroad",
            fictionId = "rr:42",
            chapterId = "rr:42:7",
            title = "1 new chapter in Mother of Learning",
            body = null,
            ts = 1_000L,
            deepLinkUri = "storyvox://reader/rr:42/rr:42:7",
            newChapterCount = 1,
            fictionTitle = "Mother of Learning",
        )
        // Second poll detects 2 more chapters — should accumulate into
        // the existing row (total 3), not stack a new one and not
        // overwrite the count with 2. Issue #1083.
        repo.record(
            sourceId = "royalroad",
            fictionId = "rr:42",
            chapterId = "rr:42:9",
            title = "2 new chapters in Mother of Learning",
            body = null,
            ts = 2_000L,
            deepLinkUri = "storyvox://reader/rr:42/rr:42:9",
            newChapterCount = 2,
            fictionTitle = "Mother of Learning",
        )

        val all = repo.observeAll().first()
        assertEquals(
            "coalescing keeps a single row per (source, fiction) while unread",
            1,
            all.size,
        )
        val row = all.first()
        assertEquals(
            "title reflects accumulated count (1 + 2 = 3), not single-poll delta",
            "3 new chapters in Mother of Learning",
            row.title,
        )
        assertEquals(3, row.newChapterCount)
        assertEquals(2_000L, row.ts)
        assertEquals("storyvox://reader/rr:42/rr:42:9", row.deepLinkUri)
    }

    @Test fun `record does not coalesce after row has been marked read`() = runTest {
        val dao = FakeInboxEventDao()
        val repo = InboxRepositoryImpl(dao)

        val firstId = repo.record(
            sourceId = "royalroad",
            fictionId = "rr:42",
            chapterId = "rr:42:7",
            title = "1 new chapter",
            body = null,
            ts = 1_000L,
            deepLinkUri = "storyvox://reader/rr:42/rr:42:7",
        )
        repo.markRead(firstId)

        // User read the first row — the next event should be a fresh
        // entry, not an in-place update.
        repo.record(
            sourceId = "royalroad",
            fictionId = "rr:42",
            chapterId = "rr:42:8",
            title = "1 new chapter (later)",
            body = null,
            ts = 2_000L,
            deepLinkUri = "storyvox://reader/rr:42/rr:42:8",
        )

        val all = repo.observeAll().first()
        assertEquals(2, all.size)
        assertEquals("1 new chapter (later)", all[0].title)
        assertEquals(false, all[0].isRead)
        assertEquals("1 new chapter", all[1].title)
        assertEquals(true, all[1].isRead)
        assertEquals(1, repo.observeUnreadCount().first())
    }

    @Test fun `record with null fictionId never coalesces`() = runTest {
        val dao = FakeInboxEventDao()
        val repo = InboxRepositoryImpl(dao)

        repo.record(
            sourceId = "kvmr",
            fictionId = null,
            chapterId = null,
            title = "KVMR live now: Morning Edition",
            body = null,
            ts = 1_000L,
            deepLinkUri = "storyvox://reader/kvmr:live/kvmr:live:0",
        )
        repo.record(
            sourceId = "kvmr",
            fictionId = null,
            chapterId = null,
            title = "KVMR live now: Local News",
            body = null,
            ts = 2_000L,
            deepLinkUri = "storyvox://reader/kvmr:live/kvmr:live:0",
        )

        val all = repo.observeAll().first()
        assertEquals(
            "source-wide events (null fictionId) always insert fresh rows",
            2,
            all.size,
        )
    }

    /**
     * Issue #1083 regression — the exact scenario from the bug report:
     * three polls coalesce before read. Poll 1 finds 2, poll 2 finds 1,
     * poll 3 finds 3. The title must say "6 new chapters", not "3".
     */
    @Test fun `record accumulates counts across three coalesced polls (issue 1083)`() = runTest {
        val dao = FakeInboxEventDao()
        val repo = InboxRepositoryImpl(dao)

        // Poll 1: 2 new chapters
        repo.record(
            sourceId = "royalroad",
            fictionId = "rr:42",
            chapterId = "rr:42:65",
            title = "2 new chapters in The Wandering Inn",
            body = null,
            ts = 1_000L,
            deepLinkUri = "storyvox://reader/rr:42/rr:42:65",
            newChapterCount = 2,
            fictionTitle = "The Wandering Inn",
        )
        // Poll 2: 1 new chapter
        repo.record(
            sourceId = "royalroad",
            fictionId = "rr:42",
            chapterId = "rr:42:67",
            title = "1 new chapter in The Wandering Inn",
            body = null,
            ts = 2_000L,
            deepLinkUri = "storyvox://reader/rr:42/rr:42:67",
            newChapterCount = 1,
            fictionTitle = "The Wandering Inn",
        )
        // Poll 3: 3 new chapters
        repo.record(
            sourceId = "royalroad",
            fictionId = "rr:42",
            chapterId = "rr:42:70",
            title = "3 new chapters in The Wandering Inn",
            body = null,
            ts = 3_000L,
            deepLinkUri = "storyvox://reader/rr:42/rr:42:70",
            newChapterCount = 3,
            fictionTitle = "The Wandering Inn",
        )

        val all = repo.observeAll().first()
        assertEquals("still one coalesced row", 1, all.size)
        val row = all.first()
        assertEquals(6, row.newChapterCount)
        assertEquals("6 new chapters in The Wandering Inn", row.title)
        // Deep link points to the most recent poll's chapter
        assertEquals("storyvox://reader/rr:42/rr:42:70", row.deepLinkUri)
        assertEquals(3_000L, row.ts)
    }

    @Test fun `markAllRead clears the unread count`() = runTest {
        val dao = FakeInboxEventDao()
        val repo = InboxRepositoryImpl(dao)

        repo.record(
            sourceId = "royalroad",
            fictionId = "rr:1",
            chapterId = "rr:1:0",
            title = "a",
            body = null,
            ts = 1L,
            deepLinkUri = null,
        )
        repo.record(
            sourceId = "royalroad",
            fictionId = "rr:2",
            chapterId = "rr:2:0",
            title = "b",
            body = null,
            ts = 2L,
            deepLinkUri = null,
        )
        assertEquals(2, repo.observeUnreadCount().first())

        repo.markAllRead()
        assertEquals(0, repo.observeUnreadCount().first())
        assertNotNull(repo.observeAll().first())
        // Rows themselves stay — only isRead flips.
        assertEquals(2, repo.observeAll().first().size)
        assertNull(repo.observeAll().first().firstOrNull { !it.isRead })
    }
}
