package `in`.jphe.storyvox.plugin.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.validate
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets

/**
 * epic/plugin-dx B1 — KSP SymbolProcessor for `@VoicePlugin`, the voice
 * twin of [SourcePluginProcessor] (#384/#1371). For each annotated
 * `VoiceEnginePlugin` implementation it generates ONE Kotlin file in
 * `in.jphe.storyvox.plugin.generated` containing a single Hilt module:
 *
 *  - `<Engine>_VoicePluginModule` (`abstract class`) — a
 *    `@Binds @IntoMap @StringKey(engineId) VoiceEnginePlugin`
 *    contribution into the `Map<String, VoiceEnginePlugin>` multibinding
 *    `VoiceEngineRegistry` consumes.
 *
 * Replaces the hand-written `VoiceEnginePluginModule` (deleted in the
 * same change): a new engine is an annotated class, zero central edits.
 * `VoiceEngineRegistry`'s init check still fails fast when the bound key
 * disagrees with the plugin's self-reported `engineId`.
 *
 * The annotation lives in `:core-playback`
 * (`in.jphe.storyvox.playback.voice.VoicePlugin`) and is looked up by
 * FQN string, exactly like `@SourcePlugin` — this module never takes a
 * compile dependency on the consumers it processes. Generated code uses
 * fully-qualified, keyword-escaped names for the same reasons documented
 * on [SourcePluginProcessor].
 */
class VoicePluginProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val annotated = resolver
            .getSymbolsWithAnnotation(VOICE_PLUGIN_FQN)
            .toList()

        val (ready, deferred) = annotated.partition { it.validate() }

        for (symbol in ready) {
            if (symbol !is KSClassDeclaration) {
                logger.error(
                    "@VoicePlugin can only be applied to a class — found $symbol",
                    symbol,
                )
                continue
            }
            val annotation = symbol.annotations.firstOrNull {
                it.shortName.asString() == "VoicePlugin" &&
                    it.annotationType.resolve().declaration.qualifiedName?.asString() == VOICE_PLUGIN_FQN
            } ?: continue

            try {
                val engineId = annotation.arguments
                    .firstOrNull { it.name?.asString() == "engineId" }
                    ?.value as? String
                    ?: error("@VoicePlugin on ${symbol.qualifiedName?.asString()} missing required engineId")
                emitModule(symbol, engineId)
            } catch (t: Throwable) {
                logger.error(
                    "Failed to emit voice plugin module for ${symbol.qualifiedName?.asString()}: ${t.message}",
                    symbol,
                )
            }
        }

        return deferred
    }

    private fun emitModule(target: KSClassDeclaration, engineId: String) {
        val targetFqn = target.qualifiedName?.asString()?.let(::escapeKotlinFqn)
            ?: error("@VoicePlugin target ${target.simpleName.asString()} has no qualified name")
        val targetSimple = target.simpleName.asString()

        val moduleSimpleName = "${targetSimple}_VoicePluginModule"

        val containingFile = target.containingFile
        val dependencies = if (containingFile != null) {
            Dependencies(aggregating = false, containingFile)
        } else {
            Dependencies.ALL_FILES
        }

        val escapedId = engineId.replace("\\", "\\\\").replace("\"", "\\\"")

        codeGenerator.createNewFile(
            dependencies = dependencies,
            packageName = GENERATED_PACKAGE_RAW,
            fileName = moduleSimpleName,
            extensionName = "kt",
        ).use { out ->
            OutputStreamWriter(out, StandardCharsets.UTF_8).use { writer ->
                writer.write(
                    buildString {
                        appendLine("// Generated by :core-plugin-ksp from @VoicePlugin($escapedId) — DO NOT EDIT.")
                        appendLine("@file:Suppress(\"RedundantVisibilityModifier\", \"unused\")")
                        appendLine()
                        appendLine("package $GENERATED_PACKAGE_KOTLIN")
                        appendLine()
                        appendLine("@dagger.Module")
                        appendLine("@dagger.hilt.InstallIn(dagger.hilt.components.SingletonComponent::class)")
                        appendLine("internal abstract class $moduleSimpleName {")
                        appendLine("    @dagger.Binds")
                        appendLine("    @javax.inject.Singleton")
                        appendLine("    @dagger.multibindings.IntoMap")
                        appendLine("    @dagger.multibindings.StringKey(\"$escapedId\")")
                        appendLine("    abstract fun bindVoiceEnginePlugin(")
                        appendLine("        impl: $targetFqn,")
                        appendLine("    ): $VOICE_ENGINE_PLUGIN_FQN")
                        appendLine("}")
                    },
                )
            }
        }

        logger.info(
            "Generated $GENERATED_PACKAGE_RAW.$moduleSimpleName for @VoicePlugin($escapedId) on $targetFqn",
            target,
        )
    }

    /** See [SourcePluginProcessor.escapeKotlinFqn] — same keyword rules. */
    private fun escapeKotlinFqn(fqn: String): String =
        fqn.split('.').joinToString(".") { segment ->
            if (segment in KOTLIN_HARD_KEYWORDS) "`$segment`" else segment
        }

    private companion object {
        private val KOTLIN_HARD_KEYWORDS = setOf(
            "as", "break", "class", "continue", "do", "else", "false", "for",
            "fun", "if", "in", "interface", "is", "null", "object", "package",
            "return", "super", "this", "throw", "true", "try", "typealias",
            "typeof", "val", "var", "when", "while",
        )
        const val VOICE_PLUGIN_FQN = "in.jphe.storyvox.playback.voice.VoicePlugin"
        const val GENERATED_PACKAGE_RAW = "in.jphe.storyvox.plugin.generated"
        const val GENERATED_PACKAGE_KOTLIN = "`in`.jphe.storyvox.plugin.generated"
        const val VOICE_ENGINE_PLUGIN_FQN = "`in`.jphe.storyvox.playback.voice.VoiceEnginePlugin"
    }
}

/**
 * Second SymbolProcessorProvider in this jar — registered alongside
 * [SourcePluginProcessorProvider] in the same
 * `META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider`
 * (java SPI supports one entry per line).
 */
class VoicePluginProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        VoicePluginProcessor(environment.codeGenerator, environment.logger)
}
